services:
  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"
  backend:
    build: ./backend/
    volumes:
      - ./backend:/app/
      - /app/backend/venv/
    ports:
      - "8000:80"
